import logging
from typing import List, Dict, Tuple, Optional
from app.db.models import SourceCitation, SearchResultItem
from app.db.repositories import metadata_repo

logger = logging.getLogger(__name__)


class CitationValidator:
    """Mandatory citation validation adhering to Section 9.

    Never display raw source citations generated by the LLM without backend validation.
    """

    @staticmethod
    def validate_citations(
        claimed_source_ids: List[str],
        retrieved_items: List[SearchResultItem],
    ) -> Tuple[List[SourceCitation], bool]:
        """Validate claimed source IDs against retrieved items and database.

        Returns: (validated_citations, is_valid)
        """
        allowed_map: Dict[str, SearchResultItem] = {}
        for item in retrieved_items:
            allowed_map[item.chunk_id] = item
            allowed_map[item.chunk_id[:8]] = item
            if "-" in item.chunk_id:
                allowed_map[item.chunk_id.split("-")[0]] = item

        validated: List[SourceCitation] = []
        has_invalid = False

        for sid in claimed_source_ids:
            clean_id = sid.strip()
            if clean_id not in allowed_map:
                logger.warning(f"Citation validation failure: fabricated source_id '{clean_id}'")
                has_invalid = True
                continue

            item = allowed_map[clean_id]
            meta = item.metadata

            # Resolve book/chapter/page directly from trusted metadata/db
            citation = SourceCitation(
                chunk_id=item.chunk_id,
                document_id=item.document_id,
                book=meta.get("book") or "गायत्री महाविज्ञान",
                chapter=meta.get("chapter"),
                section=meta.get("section"),
                page_start=int(meta.get("page_start", 1)),
                page_end=int(meta.get("page_end", 1)),
                source_type=meta.get("source_type", "book"),
            )
            validated.append(citation)

        # Deduplicate citations by chunk_id
        unique_citations = []
        seen = set()
        for c in validated:
            if c.chunk_id not in seen:
                seen.add(c.chunk_id)
                unique_citations.append(c)

        is_valid = not has_invalid and len(unique_citations) > 0
        return unique_citations, is_valid

    @staticmethod
    def resolve_citation(chunk_id: str) -> Optional[SourceCitation]:
        """Directly resolve a chunk citation from database."""
        chunk = metadata_repo.get_chunk(chunk_id)
        if not chunk:
            return None
        return SourceCitation(
            chunk_id=chunk.chunk_id,
            document_id=chunk.document_id,
            book=chunk.book or "गायत्री महाविज्ञान",
            chapter=chunk.chapter,
            section=chunk.section,
            page_start=int(chunk.page_start),
            page_end=int(chunk.page_end),
            source_type=chunk.source_type,
        )


citation_validator = CitationValidator()
